apiVersion: v1
kind: Service
metadata:
  labels:
    app: jitsu-server
  name: jitsu-server
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "2375"
      port: 2375
      targetPort: 2375
  selector:
    app: jitsu-server
status:
  loadBalancer: {}