apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-users
  name: redis-users
spec:
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6379
  selector:
    app: redis-users
status:
  loadBalancer: {}
